package com.prototype.restaurante_el_negro.enums;

public enum InitCategories {
    LACTEOS,
    BEBIDAS,
    CARNES,
    VERDURAS,
    FRUTAS,
    PANIFICADOS,
    PESCADOS_Y_MARISCOS,
    EMBUTIDOS,
    CONGELADOS,
    HARINAS_Y_CEREALES,
    LEGUMBRES,
    PASTAS,
    CONSERVAS,
    CONDIMENTOS_Y_ESPECIAS,
    ACEITES_Y_GRASAS,
    AZUCARES_Y_ENDULZANTES,
    SNACKS_Y_BOTANAS,
    HUEVOS,
    PRODUCTOS_DE_LIMPIEZA,
    DESECHABLES_Y_ENVASES,
    PRODUCTOS_DE_PANTRY,
    POSTRES_Y_REPOSTERIA,
    SALSAS_Y_ADEREZOS,
    CAFE_Y_TE

}
